controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - abb_irb4600_joint_1
      - abb_irb4600_joint_2
      - abb_irb4600_joint_3
      - abb_irb4600_joint_4
      - abb_irb4600_joint_5
      - abb_irb4600_joint_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

forward_command_controller_position:
  ros__parameters:
    joints:
      - abb_irb4600_joint_1
      - abb_irb4600_joint_2
      - abb_irb4600_joint_3
      - abb_irb4600_joint_4
      - abb_irb4600_joint_5
      - abb_irb4600_joint_6
    interface_name: position
